version: "3"

services:

  node:
    image: tezedge/tezedge:latest
    command: ["--network=mainnet", "--p2p-port=9732", "--rpc-port=18732", "--websocket-address=0.0.0.0:4927", "--peer-thresh-low", "30", "--peer-thresh-high", "45", "--tezos-context-storage=${TEZOS_CONTEXT_STORAGE:-irmin}"]
    hostname: node
    ports:
      - "4927:4927"
      - "19732:9732"
      - "18732:18732"
    networks:
      - default
    tty: true

  explorer:
    image: tezedge/tezedge-explorer:latest
    hostname: explorer
    environment:
      API: '[{"id":"localhost","name":"rust.dev.mainnet.localhost","http":"http://localhost:18732","p2p_port":9732,"features":[{"name":"ws","url":"ws://localhost:4927"},{"name":"commit","id":""},{"name":"monitoring"},{"name":"mempool"},{"name":"storage"}]}]'
    ports:
      - "80:80"
      - "8080:80"
    networks:
      - default
    tty: true