[package]
name = "shell_automaton_testing"
version = "1.11.0"
edition = "2018"

[dependencies]
bytes = "1.0.1"
serde = { version = "1.0", features = ["derive", "rc"] }

shell_automaton = { path = "../" }
crypto = { path = "../../crypto" }
storage = { path = "../../storage" }
networking = { path = "../../networking" }
tezos_encoding = { path = "../../tezos/encoding" }
tezos_identity = { path = "../../tezos/identity" }
tezos_messages = { path = "../../tezos/messages" }
