version: "3"

services:

  tezos-endorer-010-PtGRANAD:
    image: tezos/tezos:v9-release
    user: "0"
    hostname: tezos-endorser-010-PtGRANAD
    environment:
      - PROTOCOL=010-PtGRANAD
      - DATA_DIR=/data/data
      - NODE_HOST=${NODE_HOST}
      - NODE_RPC_PORT=${NODE_RPC_PORT}
    command: tezos-endorser ${DELEGATE_ALIAS} --keep-alive
    network_mode: host
    volumes:
      - "data-dir-010-PtGRANAD:/data:rw"

volumes:
  data-dir-010-PtGRANAD:
    external: true