version: "3"

services:
  tezos-client:
    image: tezos/tezos:v9-release
    user: "0"
    hostname: tezos-client
    environment:
      - PROTOCOL=010-PtGRANAD
      - DATA_DIR=/data/data
      - NODE_HOST=${NODE_HOST}
      - NODE_RPC_PORT=${NODE_RPC_PORT}
    command: tezos-client activate account ${DELEGATE_ALIAS} with "/baker.faucet.json"
    network_mode: host
    volumes:
      - "data-dir-010-PtGRANAD:/data:rw"
      - "${DELEGATE_FAUCET_JSON_FILE}:/baker.faucet.json:ro"

volumes:
  data-dir-010-PtGRANAD:
    external: true