version: "3"

services:
  tezos-client:
    image: tezos/tezos:v9-release
    user: "0"
    hostname: tezos-client
    environment:
      - PROTOCOL=010-PtGRANAD
      - DATA_DIR=/data/data
      - NODE_HOST=${NODE_HOST}
      - NODE_RPC_PORT=${NODE_RPC_PORT}
    command: tezos-client register key ${DELEGATE_ALIAS} as delegate
    network_mode: host
    volumes:
      - "data-dir-010-PtGRANAD:/data:rw"

volumes:
  data-dir-010-PtGRANAD:
    external: true