[package]
name = "tezos_interop_callback"
version = "0.10.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
# patched version of v.0.4.4 - once new version of ocaml interop
# is integrated git reference should be no longer used
ocaml-interop = { git="https://github.com/simplestaking/ocaml-interop/", branch="v0.4.4_saddr_fix"}
# local dependencies
tezos_context = { path = "../context" }
