name: audit

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.60.0
      - name: install cargo-audit
        run: cargo install cargo-audit
      - name: audit dependencies
        run: cargo audit
